---
title: "MiCAP Models"
# author: "Jessica Aldous"
# date: "2025-02-03"
author:  starcap.app@umich.edu
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Decipher]:https://jcaldous.shinyapps.io/app_decipher_jca/ 
[STARCAP]: https://umich-biostatistics.shinyapps.io/star-cap/
[OCCAM]: https://umich-biostatistics.shinyapps.io/occam/
[Integrated Model]: https://elizabethchase.shinyapps.io/Integrated_App/ 

[OCCAM Paper]:https://elizabethchase.github.io/files/chase_occam.pdf
[STARCAp Paper]:https://pubmed.ncbi.nlm.nih.gov/33090219/

### Model Applications
1. [**STARCAP Model**][STARCAP]: This Shiny app generates predictions from the prostate cancer staging system of [Dess et al. (2020)][STARCAp Paper].

2. [**OCCAM Model**][OCCAM]: This Shiny app generates predictions of other-cause mortality in prostate cancer patients using the OCCAM model of [Chase et al. (2022)][OCCAM Paper]. 
  
3. [**Integrated Model**][Integrated Model]: This app makes treatment recommendations for men with prostate cancer that incorporate both prostate cancer information and more general patient characteristics
 

Disclaimer: The content provided in the apps above does not provide medical advice. By proceeding, you acknowledge that viewing or use of this content does not create a medical professional-patient relationship, and does not constitute an opinion, medical advice, professional service or treatment recommendation of any condition. Content provided is for educational purposes only. The information and Content provided are not substitutes for medical or professional care, and you should not use the information in place of a visit, call, consultation or the advice of your physician or other healthcare provider. You are liable or responsible for any advice, course of treatment, or any other information, services that are based on Content through this site.


<details>
  <summary>Works in Progress</summary>
  1. [Integrated Model with Decipher][Decipher]: This application is a preliminary model which makes treatment recommendations for men with prostate cancer that incorporate both prostate cancer information, decipher genomic scores, and more general patient characteristics.

</details>




